//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobApp.DAL.Infrastructure
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ApplicationsContext : DbContext
    {
        public ApplicationsContext()
            : base("name=ApplicationsContext")
        {
            Type _dependency = typeof(System.Data.Entity.SqlServer.SqlProviderServices);
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<disability> disabilities { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Race> Races { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<veteran> veterans { get; set; }
    }
}
