//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobApp.DAL.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int ApplicationID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public int StateID { get; set; }
        public int CountryID { get; set; }
        public string linkedin { get; set; }
        public string website { get; set; }
        public string hear { get; set; }
        public int GenderID { get; set; }
        public int RaceID { get; set; }
        public int VeteranID { get; set; }
        public int DisabilityID { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual disability disability { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Race Race { get; set; }
        public virtual State State { get; set; }
        public virtual veteran veteran { get; set; }
    }
}
